name: Deploy Sanity Studio Otomatis

on:
  push:
    branches:
      - main # Sesuaikan kalau nama branch lu master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Ambil Kode dari Repo
        uses: actions/checkout@v4

      - name: Install NodeJS Versi Terbaru
        uses: actions/setup-node@v4
        with:
          node-version: 22 # Menggunakan Node 22 yang aman dan didukung penuh

      - name: Install Dependencies
        run: npm install

      - name: Jalankan Deploy ke Sanity Cloud
        run: npx sanity deploy --yes
        env:
          SANITY_AUTH_TOKEN: ${{ secrets.SANITY_AUTH_TOKEN }}
